# series

In [382]:
import pandas as pd
obj = pd.Series([1,2,3,4,5])

In [383]:
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [384]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [385]:
obj.values

array([1, 2, 3, 4, 5], dtype=int64)

In [386]:
obj2 = pd.Series([10,20,30,40], index=['a', 'b', 'c','d'])

In [387]:
obj2

a    10
b    20
c    30
d    40
dtype: int64

In [388]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [389]:
obj2[['a','b','c']]

a    10
b    20
c    30
dtype: int64

In [390]:
obj2['a']

10

In [391]:
obj2[obj2 > 10]

b    20
c    30
d    40
dtype: int64

In [392]:
obj2*2

a    20
b    40
c    60
d    80
dtype: int64

In [393]:
60 in obj2

False

In [399]:
'a'and'e' in obj2

False

In [23]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [24]:
obj3 = pd.Series(sdata)

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
obj3.index

Index(['Ohio', 'Texas', 'Oregon', 'Utah'], dtype='object')

In [28]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [34]:
obj4 = pd.Series(sdata, index=states)

In [35]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [37]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [38]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [39]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [40]:
obj3.index.name='State'

In [41]:
obj3

State
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [42]:
obj3.name='Population'

In [43]:
obj3

State
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
Name: Population, dtype: int64

#DataFRame

In [48]:
data = {'state':['Ohio', 'California','Nevada' ], 'Year' :[2000, 2001, 2002], 'pop':[1.5, 1.9,1.8]}

In [50]:
data1 = pd.DataFrame(data)

In [54]:
data1 

state  Year  pop
0        Ohio  2000  1.5
1  California  2001  1.9
2      Nevada  2002  1.8

In [66]:
data1 = pd.DataFrame(data,columns = ['Year', 'pop', 'state'],index=['one', 'two', 'three'])

In [67]:
data1.columns

Index(['Year', 'pop', 'state'], dtype='object')

In [68]:
data1[['state','Year']]

state  Year
one          Ohio  2000
two    California  2001
three      Nevada  2002

In [79]:
data1['Eastern']=data1['state']=='Ohio'

In [80]:
data1

Year  pop       state  Eatsern  Eastern
one    2000  1.5        Ohio     True     True
two    2001  1.9  California    False    False
three  2002  1.8      Nevada    False    False

In [82]:
del data1['Eatsern']

In [83]:
data1

Year  pop       state  Eastern
one    2000  1.5        Ohio     True
two    2001  1.9  California    False
three  2002  1.8      Nevada    False

In [85]:
data1.columns

Index(['Year', 'pop', 'state', 'Eastern'], dtype='object')

In [86]:
data1.T

one         two   three
Year     2000        2001    2002
pop       1.5         1.9     1.8
state    Ohio  California  Nevada
Eastern  True       False   False

In [92]:
data1.index.name='Index'

In [93]:
data1.columns.name='Details'

In [94]:
data1

Details  Year  pop       state  Eastern
Index                                  
one      2000  1.5        Ohio     True
two      2001  1.9  California    False
three    2002  1.8      Nevada    False

In [95]:
data1.values

array([[2000, 1.5, 'Ohio', True],
       [2001, 1.9, 'California', False],
       [2002, 1.8, 'Nevada', False]], dtype=object)

In [108]:
'state' in data1.columns

True

In [109]:
drop

<bound method Index.unique of Index(['one', 'two', 'three'], dtype='object', name='Index')>

#Reindexing

In [122]:
d1 = pd.Series(['Data Science', 'Python', 'AI', 'ML'], index= ['d','b','c','a'])

In [123]:
d1.index.name='Index'

In [124]:
d1

Index
d    Data Science
b          Python
c              AI
a              ML
dtype: object

In [131]:
d2 = d1.reindex(['a','b','c','d','e','f'],fill_value=0)

In [133]:
d2

Index
a              ML
b          Python
c              AI
d    Data Science
e               0
f               0
dtype: object

In [1]:
obj3 = pd.Series(['Blue', 'Yellow', 'Green'], index=[0,2,4])
obj3

NameError: name 'pd' is not defined

In [136]:
obj3.reindex(range(6), method='ffill')

0      Blue
1      Blue
2    Yellow
3    Yellow
4     Green
5     Green
dtype: object

In [137]:
obj3

0      Blue
2    Yellow
4     Green
dtype: object

In [140]:
import numpy as np
df = pd.DataFrame(np.arange(9).reshape(3,3), index=['a','b','c'], columns=['Brampton','Hamilton', 'Malton'])

In [141]:
df

Brampton  Hamilton  Malton
a         0         1       2
b         3         4       5
c         6         7       8

In [143]:
df = df.reindex(['a','b','c','d'])

In [144]:
df

Brampton  Hamilton  Malton
a       0.0       1.0     2.0
b       3.0       4.0     5.0
c       6.0       7.0     8.0
d       NaN       NaN     NaN

In [145]:
state=['Texas','Utah', 'Brampton', 'Malton']
df.reindex(columns=state)

Texas  Utah  Brampton  Malton
a    NaN   NaN       0.0     2.0
b    NaN   NaN       3.0     5.0
c    NaN   NaN       6.0     8.0
d    NaN   NaN       NaN     NaN

In [163]:
df = df.reindex(index=['a','b','c','e'], columns=state, fill_value=0)
df

Texas  Utah  Brampton  Malton
a    0.0   0.0       0.0     2.0
b    0.0   0.0       3.0     5.0
c    0.0   0.0       6.0     8.0
e    0.0   0.0       0.0     0.0

# Dropping enteries from axis

In [164]:
df.drop('e')

Texas  Utah  Brampton  Malton
a    0.0   0.0       0.0     2.0
b    0.0   0.0       3.0     5.0
c    0.0   0.0       6.0     8.0

In [166]:
df.drop('Texas', axis=1)

Utah  Brampton  Malton
a   0.0       0.0     2.0
b   0.0       3.0     5.0
c   0.0       6.0     8.0
e   0.0       0.0     0.0

#indexing

In [205]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [206]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [207]:
data['one']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32

In [208]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [209]:
data[1:]


one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [210]:
data[data['three']>6]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [216]:
data.values[2]

array([ 8,  9, 10, 11])

In [254]:
area = pd.Series({'California': 423967, 'Texas': 695662,'New York': 141297, 'Florida': 170312,'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,'New York': 19651127, 'Florida': 19552860,'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [255]:
data.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [256]:
data.columns


Index(['area', 'pop'], dtype='object')

In [257]:
data['density'] = data['area']/data['pop']

In [258]:
data

area       pop   density
California  423967  38332521  0.011060
Texas       695662  26448193  0.026303
New York    141297  19651127  0.007190
Florida     170312  19552860  0.008710
Illinois    149995  12882135  0.011644

In [259]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 1.10602431e-02],
       [6.95662000e+05, 2.64481930e+07, 2.63028177e-02],
       [1.41297000e+05, 1.96511270e+07, 7.19027463e-03],
       [1.70312000e+05, 1.95528600e+07, 8.71033700e-03],
       [1.49995000e+05, 1.28821350e+07, 1.16436445e-02]])

In [260]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 1.10602431e-02])

In [261]:
data.loc[:'Texas',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193

In [262]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [263]:
data.iloc[1:,1:]

pop   density
Texas     26448193  0.026303
New York  19651127  0.007190
Florida   19552860  0.008710
Illinois  12882135  0.011644

In [264]:
data.loc[data.area>141297,['pop','density']]

pop   density
California  38332521  0.011060
Texas       26448193  0.026303
Florida     19552860  0.008710
Illinois    12882135  0.011644

In [265]:
data.iloc[0,1]

38332521

In [253]:
data

area       pop   density
California  423967      Full  0.011060
Texas       695662  26448193  0.026303
New York    141297  19651127  0.007190
Florida     170312  19552860  0.008710
Illinois    149995  12882135  0.011644

In [266]:
data.iloc[0,2]="FULL"

In [267]:
data

area       pop     density
California  423967  38332521        FULL
Texas       695662  26448193   0.0263028
New York    141297  19651127  0.00719027
Florida     170312  19552860  0.00871034
Illinois    149995  12882135   0.0116436

In [270]:
data[1:4]

area       pop     density
Texas     695662  26448193   0.0263028
New York  141297  19651127  0.00719027
Florida   170312  19552860  0.00871034

In [271]:
data['Texas':'Florida']

area       pop     density
Texas     695662  26448193   0.0263028
New York  141297  19651127  0.00719027
Florida   170312  19552860  0.00871034

# NULL Values

In [272]:
data = pd.Series([1, np.nan, 'hello', None])

In [273]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [274]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [276]:
data[data.notnull()]

0        1
2    hello
dtype: object

# Dropping null values

In [279]:
data.dropna()

0        1
2    hello
dtype: object

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame([[1, np.nan, 2],[2, 3, 5],[np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [3]:
df.dropna()  # dropna() will drop all rows in which any null value is present:

0    1  2
1  2.0  3.0  5

In [4]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [5]:
df.dropna(axis='columns', how='all') #The default is how='any', such that any row or column (depending on the axis key word) containing a null value will be dropped

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [8]:
df.dropna(axis='rows', thresh=2) #Delete those rows that are having less than 2 non-null values

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [15]:
df[0].max()

2.0

In [333]:
import pandas as pd
series1 = pd.Series(range(100,110))
series2 = pd.Series(['A','B','C','D','E','F','G','H','I'])
pd.DataFrame({'number':series1, 'value':series2})

number value
0     100     A
1     101     B
2     102     C
3     103     D
4     104     E
5     105     F
6     106     G
7     107     H
8     108     I
9     109   NaN

In [334]:
print("Original Series:")
print(series1)
print(series2)

df = pd.concat([series1, series2], axis=1)
print("\nStack two given series vertically and horizontally:")
print(df)


Original Series:
0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64
0    A
1    B
2    C
3    D
4    E
5    F
6    G
7    H
8    I
dtype: object

Stack two given series vertically and horizontally:
     0    1
0  100    A
1  101    B
2  102    C
3  103    D
4  104    E
5  105    F
6  106    G
7  107    H
8  108    I
9  109  NaN


#Date Time

In [342]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04','2015-07-04', '2015-08-04'])
data = pd.Series([0, 1, 2, 3], index=index)
data


2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [344]:
data['2014-07-04':'2015-07-04']

2014-07-04    0
2014-08-04    1
2015-07-04    2
dtype: int64

In [347]:
import datetime
dates = pd.to_datetime([datetime.datetime(2015, 7, 3), '4th of July, 2015','2015-Jul-6', '07-07-2015', '20150708'])
dates

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[ns]', freq=None)

In [349]:
pd.date_range('2015-07-03', '2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [350]:
pd.date_range('2015-07-03', periods=8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [351]:
pd.date_range('2015-07-03', periods=8, freq="H")

DatetimeIndex(['2015-07-03 00:00:00', '2015-07-03 01:00:00',
               '2015-07-03 02:00:00', '2015-07-03 03:00:00',
               '2015-07-03 04:00:00', '2015-07-03 05:00:00',
               '2015-07-03 06:00:00', '2015-07-03 07:00:00'],
              dtype='datetime64[ns]', freq='H')

In [352]:
pd.period_range('2015-07', periods=8, freq='M')

PeriodIndex(['2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
             '2016-01', '2016-02'],
            dtype='period[M]', freq='M')

In [1]:
a = pd.date_range('2025-04-05', periods = 8)
df = pd.DataFrame(a, columns={'datetime'})
df

NameError: name 'pd' is not defined

In [378]:
df['ts'] = df.datetime.values.astype(np.int64)

In [379]:
df

datetime                   ts
0 2025-04-05  1743811200000000000
1 2025-04-06  1743897600000000000
2 2025-04-07  1743984000000000000
3 2025-04-08  1744070400000000000
4 2025-04-09  1744156800000000000
5 2025-04-10  1744243200000000000
6 2025-04-11  1744329600000000000
7 2025-04-12  1744416000000000000